# Generated by Django 4.0.5 on 2023-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlineOrg', models.CharField(max_length=300)),
                ('headlineEng', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=30)),
                ('articleUrl', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('webisteUrl', models.CharField(max_length=300)),
                ('language', models.CharField(choices=[('Turkish', 'Turkish'), ('English', 'English'), ('Arabic', 'Arabic'), ('Farsi', 'Farsi')], max_length=30)),
                ('artilce', models.ManyToManyField(blank=True, to='NewsScrapper.newsarticle')),
            ],
        ),
    ]
